export enum TipoDeServicio {
    PELUQUERIA = "PELUQUERIA",
    MANICURA = "MANICURA",
    PEDICURA = "PEDICURA",
    LIMPIEZAFACIAL = "LIMPIEZAFACIAL",
    MASAJES = "MASAJES",
    DEPILACION = "DEPILACION",
    MAQUILLAJE = "MAQUILLAJE",
    BRONCEADO = "BRONCEADO",
    BARBERIA = "BARBERIA",
}
